language: node_js
node_js:
    - '4.4'
before_script:
    - npm install
script: gulp test
after_success:
    # CREATE GIT TAG
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
    - echo -n $GIT_TAG > public/version
    - git remote add origin https://$GITHUBKEY@github.com/Microsoft/PowerBI-JavaScript > /dev/null 2>&1
    - git add dist/ -f
    - git commit -m "Generated distribution files for $TRAVIS_BUILD_NUMBER"
    - git push --quiet origin $TRAVIS_BRANCH > /dev/null 2>&1
    - git commit -m "Set build VERSION number" public/version
    - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
    - git push --quiet origin $TRAVIS_BRANCH $GIT_TAG > /dev/null 2>&1
branches:
    except:
        - /^build-[0-9a-z\-]*/